# Created by: Cedric Ricard <ricard+freebsd@free.fr>
# $FreeBSD: $

PORTNAME=	django-filter
PORTVERSION=	0.8
CATEGORIES=	www python
MASTER_SITES=	CHEESESHOP
PKGNAMEPREFIX=	${PYTHON_PKGNAMEPREFIX}

MAINTAINER=	ricard+freebsd@free.fr
COMMENT=	Django-filter is a reusable Django application for allowing users to filter querysets dynamically.

LICENSE=	BSD

RUN_DEPENDS=	${PYTHON_PKGNAMEPREFIX}django>=1.4.5:${PORTSDIR}/www/py-django

USES=		python
USE_PYTHON=	autoplist distutils

.include <bsd.port.mk>
