# Created by: Cedric Ricard <ricard+freebsd@free.fr>
# $FreeBSD: $

PORTNAME=	mogo
PORTVERSION=	0.2.4
CATEGORIES=	databases python
MASTER_SITES=	CHEESESHOP
PKGNAMEPREFIX=	${PYTHON_PKGNAMEPREFIX}

MAINTAINER=	ricard+freebsd@free.fr
COMMENT=	Simple PyMongo "schema-less" object wrapper.

LICENSE=	APACHE2

RUN_DEPENDS=	pymongo>=2.8:${PORTSDIR}/databases/pymongo

USES=		python
USE_PYTHON=	autoplist distutils

.include <bsd.port.mk>
