# Created by: Cedric Ricard <ricard+freebsd@free.fr>
# $FreeBSD: $

PORTNAME=	django-rest-framework
PORTVERSION=	2.4.4
CATEGORIES=	www python
MASTER_SITES=	CHEESESHOP
PKGNAMEPREFIX=	${PYTHON_PKGNAMEPREFIX}

MAINTAINER=	ricard+freebsd@free.fr
COMMENT=	Django REST framework is a powerful and flexible toolkit that makes it easy to build Web APIs

LICENSE=	BSD

RUN_DEPENDS=	${PYTHON_PKGNAMEPREFIX}django>0:${PORTSDIR}/www/py-django

USES=		python
USE_PYTHON=	autoplist distutils

.include <bsd.port.mk>
